{% set name = "mofchecker" %}
{% set version = "0.9.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mofchecker-{{ version }}.tar.gz
  sha256: cc97b9a4a9ce04220759a3918e9a4600c6f00d7e81fdf7e4219f44e782371325

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mofchecker = mofchecker.cli:main


requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click ==7.*
    - networkx ==2.*
    - pymatgen <2023,>=2022.0.12
    - python >={{ python_min }}
    - openbabel ==3.*
    - backports.cached-property ==1.*
    - pyyaml ==5.*
    - ase ==3.*
    - structuregraph-helpers
    - element-coder
    - libconeangle

test:
  requires:
    - python {{ python_min }}
  imports:
    - mofchecker

about:
  home: https://github.com/kjappelbaum/mofchecker
  summary: Perform sanity checks on MOF structures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kjappelbaum
